name: Build LaTeX document and uploads

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuscript/**'

jobs:

  pdf-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: manuscript/
          root_file: ./main.tex
      - name: Uploads release
        uses: actions/upload-artifact@v2
        with:
          name: manuscript
          path: ./manuscript/main.pdf